services:
  db:
    image: postgres:16-alpine
    container_name: smartlogist-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: smartlogist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    container_name: smartlogist-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
